version: '2'
services:
    rodoscupmanager-app:
        image: rodoscupmanager
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rodoscupmanager-postgresql:5432/RodosCupManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rodoscupmanager-postgresql:
        extends:
            file: postgresql.yml
            service: rodoscupmanager-postgresql
